Fix clang warning (#1148)
Summary:
**Pre-submission checklist**
- [x] I've ran the linters locally and fixed lint errors related to the files I modified in this PR. You can install the linters by running `pip install -r requirements-dev.txt && pre-commit install`
- [x] `pre-commit run`

The build was failing with -Werror on clang due to a range-loop copying a SwitchID value instead of taking it by reference:

AgentMirrorOnDropDnxTests.cpp:514: error: loop variable 'switchId' creates a copy
note: use reference type 'const value_type &' (aka 'const facebook::fboss::SwitchID &') to prevent copying
HwAsicTable::getSwitchIDs() returns a container of SwitchID (a non-trivial wrapper type), so clang flags the implicit per-iteration copy. The fix changes const auto to const auto& in the WITH_RETRIES_N loop in MtuTrapStillWorks, matching the convention used elsewhere in the file.

Pull Request resolved: https://github.com/facebook/fboss/pull/1148

Test Plan: CI build and existing tests passing.

Reviewed By: jasmeetbagga

Differential Revision: D103733630

Pulled By: joseph5wu

fbshipit-source-id: 9caae419ecc7d78565452308fb2ada01b37a5627